# Generated by Django 4.0 on 2022-02-06 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotter_app', '0002_group_post_group_user_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='name',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
