# Generated by Django 4.0 on 2022-02-06 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotter_app', '0005_alter_user_bio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='group',
        ),
        migrations.AddField(
            model_name='group',
            name='group_users',
            field=models.ManyToManyField(related_name='joined_groups', to='spotter_app.User'),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.TextField(default='Anonymous Gym Goer'),
        ),
    ]
