# Generated by Django 4.0 on 2022-02-06 04:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spotter_app', '0006_remove_user_group_group_group_users_alter_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='parent_post',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='post_comments', to='spotter_app.post'),
            preserve_default=False,
        ),
    ]
